### ISSUE TITLE
wget does not work due to recent security changes ....

### ISSUE THREAD

**Issue by gfyllos** [emericg/OpenSubtitlesDownload#100]
Just noticed the script i use to automatically search and download  subtitles does not work, apparently due to security enchantments....
Here's what happens: my script signs in , selects a subtitle and the issues wget  which responds as follows:

_$ wget http://dl.opensubtitles.org/en/download/src-api/vrf-19cf0c5a/sid-NIY4l9y3Aj30RRnFLcXNeGO0nj6/filead/1957531774.gz 
--2023-10-22 10:23:31--  http://dl.opensubtitles.org/en/download/src-api/vrf-19cf0c5a/sid-NIY4l9y3Aj30RRnFLcXNeGO0nj6/filead/1957531774.gz
Resolving dl.opensubtitles.org (dl.opensubtitles.org)... 172.64.102.24, 172.64.103.24, 2606:4700:e0::ac40:6618, ...
Connecting to dl.opensubtitles.org (dl.opensubtitles.org)|172.64.102.24|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-10-22 10:23:31 ERROR 403: Forbidden_

Downloading the same url from firefox works only after I answer the following security question:

_Icon for dl.opensubtitles.orgdl.opensubtitles.org
Checking if the site connection is secure
dl.opensubtitles.org needs to review the security of your connection before proceeding._

Any ides how to solve the above? 
thanks

**Comment by FriendlyTroll** [comment]
Hi,

I believe this is due to new API requirement. See my response [here](https://github.com/emericg/OpenSubtitlesDownload/issues/95#issuecomment-1787079698)

**Comment by emericg** [comment]
Looks like it's going through a manual verification from cloudfare, which cannot really succeed :)
Can you try again with the very latest version of this script, running with the new REST API?
