### ISSUE TITLE
Urllib Error

### ISSUE THREAD

**Issue by KEM-Spain** [emericg/OpenSubtitlesDownload#104]
>> Enter your choice (0-30): 6
Urllib error ( 400 )  Bad Request
>> An error occurred while connecting to the OpenSubtitles.com server

Using:  OpenSubtitlesDownload.py / Version 6.0

After selecting a file to download the error occurs.

**Comment by qtaped** [comment]
Same error here (even before choosing a file to dl), using last version (6.2) in CLI (macOS and debian).

**Comment by KEM-Spain** [comment]
Yeah.  The site has messed things up.  Fails from Kodi as well.

**Comment by emericg** [comment]
> Urllib error ( 400 ) Bad Request

That's weird, do you have this error every time you use the script? I've never had this one, while testing on linux and macOS.
Anything particular in your setups that could explain why it's behaving differently? VPN, weird Internet setup?

> Yeah.  The site has messed things up.  Fails from Kodi as well.

Kodi is still using the "old" API so it will only work if you have a VIP account.

**Comment by KEM-Spain** [comment]
Nothing unorthodox.  No intermediate apps or hardware.  Python is up to
date on Ubuntu 23.10.  Used to work flawlessly.
Cloudflare?

**Comment by setaur** [comment]
Same error, after choosing subtitles.
Debian oldstable.

**Comment by 097115** [comment]
Same error, too.

Ubuntu 22.04.3
Python 3.10.12
urllib3 1.26.14

**Comment by pecosk** [comment]
Same error, it seems it happens when trying to login via `https://api.opensubtitles.com/api/v1/login`
The data that is being sent (username and pass) seem to be correct, they are wrapped in `b'{"username:"my_username", "password": "my_password"}'`
Not sure if that is expected, i dont have any chars that seem like invalid in json, just alphanumeric with some `!*`

**Comment by pecosk** [comment]
Looks like for me i was able to debug it .. the issue was, that i was using my email as username.
When i changed that to actual username, it works.

Hope it helps

**Comment by emericg** [comment]
> Looks like for me i was able to debug it .. the issue was, that i was using my email as username.

Yes it seems you are right, an invalid username/password causes that error. The GUI will output "login error" but the CLI will just output "Urllib error ( 400 )  Bad Request".
I'll see if I can make the error message more helpful...

**Comment by qtaped** [comment]
> Looks like for me i was able to debug it .. the issue was, that i was using my email as username. When i changed that to actual username, it worked.
> 
> Hope it helps

That was it! Working fine now, thanks!

@emericg and thanks for your work

**Comment by KEM-Spain** [comment]
Works for me as well!  Thanks 🙏
