### ISSUE TITLE
Error: [class 'KeyError'] Line: 838

### ISSUE THREAD

**Issue by YoureMySoul** [emericg/OpenSubtitlesDownload#105]
```console
$ OpenSubtitlesDownload.py --cli -t manual *E02*.mkv
>> OpenSubtitlesDownload encountered an unknown error, sorry about that...
Error: [class 'KeyError']
Line: 838
Just to be safe, please check:
- Your Internet connection status
- www.opensubtitles.com availability
- Your download limits (10 subtitles per 24h for non VIP users)
- That are using the latest version of this software ;-)
```

` Under dev ? : false `
` Allow anonymous ? : true `

My account at OpenSubtitles.com is freshly created. It wasn't working one month ago, and it still doesn't work with the latest version. I guess that the previous issue was also a "KeyError".

On the stats page, all of the statistics are currently empty.

**Comment by roberthr74** [comment]
I also error like this. Not with every title, but most of them.

Unexpected error (line 549): <class 'http.client.RemoteDisconnected'>
>> OpenSubtitlesDownload encountered an unknown error, sorry about that...
Error: [class 'TypeError']
Line: 830
Just to be safe, please check:
- Your Internet connection status
- www.opensubtitles.com availability
- Your download limits (10 subtitles per 24h for non VIP users)
- That are using the latest version of this software ;-)

**Comment by roberthr74** [comment]
Looks llike it's working now!!! Thank you so much :-)

**Comment by emericg** [comment]
No problem :) The first version using the new API was rushed to be ready on January 1st, it's bound to have a couple issues :/

**Comment by YoureMySoul** [comment]
still doesn't work but line number and error changed with the v6.1:
```console
Error: [class 'NameError']
Line: 874
```

**Comment by YoureMySoul** [comment]
Thank you for this awesome tool.
