### ISSUE TITLE
Duplicate subtle filename search mode ignores valid search result from hash when using "hash_then_filename" mode

### ISSUE THREAD

**Issue by matkook404log** [emericg/OpenSubtitlesDownload#106]
The line 823 "if ('filename' in opt_search_mode) or ('hash_then_filename' in opt_search_mode and len(subtitlesResultList['data']) == 0):" can incorrectly be executed if opt_search_mode = 'hash_then_filename'.

For example, subtitlesResultList correctly returns result from hash search, but still get executed by the "'filename' in opt_search_mode" part of the condition. As a result, valid result from hash is deleted with "0" result from filename search method.

The substring search is ambiguous and covers both cases: "hash_and_filename" and "hash_then_filename".

The first part of the condition in line 823 should specify exactly "hash_and_filename" instead of the ambiguous "filename" string only.

**Comment by emericg** [comment]
Looks like you are right, thanks for taking a look at the problem.
I've made changes so this doesn't happen anymore.
