### ISSUE TITLE
opt_search_overwrite is False

### ISSUE THREAD

**Issue by ejlkemper** [emericg/OpenSubtitlesDownload#110]
This option still searches and download the subtitle, so killing my daily counts..... ?

**Comment by emericg** [comment]
Indeed, the controls in place to detect whether a subtitle file was already present could be improved.
Can you try the new version, and if that still doesn't work for you tell me more about your use case?

**Comment by ejlkemper** [comment]
Hi,
Thanks for responding. I am not using it anymore.
I am using Bazarr now which also uses other subtitle sources.

**Comment by emericg** [comment]
No problem, thanks for reporting the bug anyhow!
