### ISSUE TITLE
API key is blocked

### ISSUE THREAD

**Issue by madurapa** [emericg/OpenSubtitlesDownload#114]
The default API key that comes with the script has been blocked by OpenSubtitles. the solution is to create a free API key for yourself.

https://www.opensubtitles.com/en/consumers

API doc: https://opensubtitles.stoplight.io/docs/opensubtitles-api/e3750fd63a100-getting-started

**Comment by emericg** [comment]
Hi, how do you know the api key is blocked?
From what I can gather, it's still working and you probably just need a proper account (as before) to use this software.

**Comment by madurapa** [comment]
I used the key in https://opensubtitles.stoplight.io/docs/opensubtitles-api/73acf79accc0a-login and got an error message saying the key is blocked and emailed instructions on how to unlock.

**Comment by emericg** [comment]
The default key is still working fine for me (and others), did you follow instructions on how to use a valid account ?

> https://github.com/emericg/OpenSubtitlesDownload/wiki/Log-in-with-a-registered-user

**Comment by madurapa** [comment]
I'm using my personal key for now. I guess it should be fine if the other has no problem.

Thank you

**Comment by emericg** [comment]
Yes you can use a personal key that's no problem.
But nobody else reported the issue, and I can still see many downloads from the stats :/

**Comment by madurapa** [comment]
Just check with the repo key.
Yes, it's working fine. I guess it was just the API false response on that day.
