### ISSUE TITLE
Syntax errors while fetching subs

### ISSUE THREAD

**Issue by Cqoicebordel** [emericg/OpenSubtitlesDownload#116]
I got a couple of different syntax errors, just after selecting a sub to download. The error is sub dependent, I mean that I get the same error each time I chose a particular sub, an another if I chose another sub.

To reproduce :   
`$ OpenSubtitlesDownload.py My.Brilliant.Friend.S02E01.The.New.Name.ITALIAN.SUBBED.720p.WEBRip.2CH.x265.HEVC-PSA.mkv`

The following popup appears : 
![Screenshot_20240911_230331](https://github.com/user-attachments/assets/4120ffd4-1834-41c2-bdaf-f9dad04248e2)

If I chose the first or third option, the full output of the command is as follow : 
```bash
x:  0   y:  0   w:  920   h:  400
/bin/sh: 1: Syntax error: Unterminated quoted string
x:  -1299055440   y:  21854   w:  920   h:  400
```

If I chose the second, I get : 
```bash
x:  0   y:  0   w:  920   h:  400
/bin/sh: 1: Syntax error: "(" unexpected (expecting ")")
x:  1160377632   y:  21956   w:  920   h:  400
```

The fact it's dependent on the subtitle chosen is weird. But it still could come from my machine which is stuck on Kubuntu 20.04.

Anyway, I hope it'll help :)

**Comment by emericg** [comment]
Hi, I'll have a look now that I have a KDE installation, but it will be with the very latest KDE 6.2 version, so it might not translate to fix for you unfortunately :(

**Comment by emericg** [comment]
I've pushed a bit of work regarding that issue, I encountered the first one you mentioned, I'll try to see if I can find some more bugs.

**Comment by Cqoicebordel** [comment]
I've retested it, and for the same file, with the same command, I get the second result (`"(" unexpected`) for the three subtitles proposed.
```bash
x:  0   y:  0   w:  940   h:  480
/bin/sh: 1: Syntax error: "(" unexpected (expecting ")")
x:  0   y:  0   w:  940   h:  480
```

And the KDialog error message is
```text
An error occurred while downloading or writing 'en' subtitles for My.Brilliant.Friend.S02E01.The.New.Name.ITALIAN.SUBBED.720p.WEBRip.2CH.x265.HEVC-PSA.mkv.
```
So it looks like the first issue is indeed fixed, but the second persists.

But this time, I have the time to search why…

So. It boils down to having parenthesis in the path of the file. I have the year of the TV show in the folder name.

I have modified two lines on the KDE path to check it's working : 
First one, https://github.com/emericg/OpenSubtitlesDownload/blob/13cce2b32bcd7f3dd18b9daa79e753a3c0257692/OpenSubtitlesDownload.py#L250
I changed to `return string`, to bypass the escape function.

Secondly,
https://github.com/emericg/OpenSubtitlesDownload/blob/13cce2b32bcd7f3dd18b9daa79e753a3c0257692/OpenSubtitlesDownload.py#L1019
I modified to
```python
process_subtitlesDownload = subprocess.call("(wget -q -O \"" + subPath + "\" " + subURL + ")  2>&1", shell=True)
```
Note the escaped double quotes added around `subPath`.

With this code, the three subtitles listed above download without a hitch.

I'm not doing a pull request, because the code is not clean, and I didn't do the gtk path of the code. But with the root issue known, should be quite straightforward to do it cleanly :)

**Comment by emericg** [comment]
That's great, thanks!
The simpler path escaping (but not just removed) and double-quoted subPath seems to do the tricks for kdialog. Can you give it a try? I think I'll release a new version with this in the next few days.

**Comment by Cqoicebordel** [comment]
I'm not sure I understand what you are saying.
If you are saying to try while keeping the call to the `escapeGUI` function, it doesn't work : I have a single quote `'` in the subPath, (the name of the show is "L'amica geniale"), it goes to the escape function, double escape the single quote, which then get single escaped in the wget command. Since it's double quoted, it keeps the backslash as part of the path, and fails.

I'm not sure why you mention kDialog, since all I changed is only in the path to the wget command.
The gui part function well, the error was from bash interpreting the path without quotes.

It's easy to reproduce : use a folder with a single quote and parenthesis, and test the code. I know the gnome codepath has the same issue as the KDE one.

**Comment by emericg** [comment]
Alright, so I rewrote mostly everything related to these string escaping, so we can handle these characters **( " ' « ` &** in files, folders and GUI strings. Hopefully we're good now ^^ Hopefully...

**Comment by Cqoicebordel** [comment]
This version seems to works OK for me, at least.

**Comment by emericg** [comment]
The KDE path doesn't use wget at all anymore, so less problems there ^^ The wget path is only there so we can have a zenity "infinite" scrolling popup, and that concept doesn't exist with kdialog.

zenity code has more escaping and can now handle the cases you mentioned in this issue.

The kdialog and CLI paths have been cleaned of all unnecessary escaping code, and un-escaping shenanigans, so everything is more straightforward.
kdialogs popup are now on top of the screen instead of bottom, and should be less oversized, what do you think about these changes?

**Comment by Cqoicebordel** [comment]
For the positions of the dialogs, they didn't change for me, probably because I moved them manually at some point.

For the rest, the changes seems good.

Only one thing : on my code, I would be wary of escaping the strings manually, when there are natives functions that can do that. It _feels_ to me like a potential opportunity for issues.

Other than that, nothing to say :)

**Comment by emericg** [comment]
> Only one thing : on my code, I would be wary of escaping the strings manually, when there are natives functions that can do that. It feels to me like a potential opportunity for issues.

I've tried some native functions, they usually escape way too much, it doesn't work well.

Anyway, thanks for bringing that issue to my attention, the fixes are in the new release!
