### ISSUE TITLE
Too Many Requests error.

### ISSUE THREAD

**Issue by fidodido48** [emericg/OpenSubtitlesDownload#117]
Hi,
Getting this error for some subs, when downloading for the whole season:
> Urllib error ( 429 )  Too Many Requests

Can you increase the wait time for each request to fix it?

**Comment by emericg** [comment]
Before it was 3s, but I changed it to 1s not too long ago, because it seemed to be working, but I got the same problem as you this week...
Let's try 2 and hope for the best then :p
