### ISSUE TITLE
Urllib error ( 400 )  Bad Request

### ISSUE THREAD

**Issue by sharinganthief** [emericg/OpenSubtitlesDownload#119]
Selected 4 different options, always 400

>> Enter your choice [0-30]: 1
Urllib error ( 400 )  Bad Request
>> An error occurred while connecting to the OpenSubtitles.com server

**Comment by emericg** [comment]
What OS are you using, what version of the software?

**Comment by sharinganthief** [comment]
windows 11, latest version - 6.3

**Comment by sharinganthief** [comment]
looks like my username was wrong
