### ISSUE TITLE
Respect opt_languages

### ISSUE THREAD

**Issue by umpirsky** [emericg/OpenSubtitlesDownload#20]
I set:
```
opt_languages = ['sr,hr']
```

It shows other languages too:

![screenshot from 2016-08-12 21-42-16](https://cloud.githubusercontent.com/assets/208957/17635054/b940e958-60d5-11e6-9cb2-17cce08827cb.png)

**Comment by emericg** [comment]
Well, it looks like you are right! The solution seems to be using only 3 letters language code (so in your case, ['scc,hrv']).
I'll look at this and maybe update the documentation of opt_languages if I don't find any fix...

**Comment by umpirsky** [comment]
@emericg That worked, thanks. It didn't work with `srp` thought.If you look at https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes you'l see that the ISO 639-2/T code srp deprecated the ISO 639-2/B code scc.

**Comment by emericg** [comment]
The changes have made their way into the 3.5 release, thanks for the report.
Regarding the scc langage code deprecated in favor of srp, that's an issue for opensubtitles.org. They maintain their "own" list of codes that's probably not updated much (http://www.opensubtitles.org/addons/export_languages.php) and that's the one we link to in the wiki ;-)

**Comment by umpirsky** [comment]
@emericg Cool. Thanks for making this awesome tool.
