### ISSUE TITLE
Exit codes

### ISSUE THREAD

**Issue by setaur** [emericg/OpenSubtitlesDownload#31]
It would be nice to have different than 0 exit code if none subtitles were found.

**Comment by emericg** [comment]
Hi,
I'm open to it but what should I put?

I was thinking about something like this:
```
# ==== Return codes ============================================================
#
# -1: Success but NO subtitles downloaded
#  0: Success and subtitles downloaded
#  2: Failure
```

**Comment by setaur** [comment]
Looks great!

**Comment by emericg** [comment]
Ok I've finally commited the following: (using negative exit code was making me nervous)
```
# ==== Exit codes ==============================================================
# 0: Success and subtitles downloaded
# 1: Success but no subtitles found
# 2: Failure
```

I will not release the next version (3.6) right away so you still got time to comment on this ;-)

**Comment by setaur** [comment]
That will work for me, thanks!
