### ISSUE TITLE
manual search downloading incorrect subtitle if there is only one option

### ISSUE THREAD

**Issue by tmottabr** [emericg/OpenSubtitlesDownload#33]
i use OpenSubtitlesDownload in cli mode only.

If i have search set to manual, fallback to search by name on and there is only one subtitle available it will be download regardless if it is the correct one or not.

If i have manual search set i believe the fallback should ask me if i want to download that subtitle even if there is only one as I want to review if it is the correct sub for my file first.

**Comment by emericg** [comment]
Hi,
Automatically downloading the 'only' subtitles available is the intended behavior indeed. IIRC it was an user request too ^^
Now I understand your issue, it's not hard to fix, but I'm not sure if I should stop doing that in CLI mode only, or add another mode like 'full manual' or something... If think the first solution might be best fitted?!

**Comment by emericg** [comment]
OK I added a new 'default' selection mode, that you can override with either manual or auto mode.
