### ISSUE TITLE
suggestion : enable and disable fallback search by name from via command argument

### ISSUE THREAD

**Issue by tmottabr** [emericg/OpenSubtitlesDownload#34]
add a tag like "--fallback" to enable fallback search by name from the command line.

I use auto mode only with the fallback disable so it will download automatically only subtitles that match my file exactly via hash. Otherwise i will do a manual search with fallback enable and manually select the appropriate sub.

**Comment by emericg** [comment]
It makes sense to add this flag, but it also means that the default search mode has to change to 'hash' only.
I might just add --search [hash,filename,both] and --download [manual,default,auto] command line options...
And / or set a different set of default options for CLI mode. I acknowledge CLI users might have different usages than the GUI users.

Inputs?

**Comment by emericg** [comment]
I added two new CLI options, search mode and selection mode.

You can now choose your search mode between hash, filename, hash_then_filename, hash_and_filename.
You can now choose your selection mode between manual, default or auto.

Let me know if that works for you.

**Comment by tmottabr** [comment]
work perfect. thanks.
