### ISSUE TITLE
Issue for multiple downloads when opt_search_overwrite == 'off'

### ISSUE THREAD

**Issue by rhcpfan** [emericg/OpenSubtitlesDownload#35]
In the following code block, for every call to `videoPathList.remove(videoPathDispatch)`, an item in `videoPathList` will be skipped (removing elements while iterating).

```python
# Check if the subtitles exists videoPathList
if opt_search_overwrite == 'off':
    for videoPathDispatch in videoPathList:
        if checkSubtitlesExists(videoPathDispatch) == True:
            videoPathList.remove(videoPathDispatch)
```

A simple solution would be to use a second array to hold the paths to remove later:

```python
paths_to_remove = []

if opt_search_overwrite == 'off':
    for videoPathDispatch in videoPathList:
        if checkSubtitlesExists(videoPathDispatch) == True:
            paths_to_remove.append(videoPathDispatch)

for path_to_remove in paths_to_remove:
    videoPathList.remove(path_to_remove)
```

Hope it helps, keep up the good work!

**Comment by rhcpfan** [comment]
Or even better, use list comprehension

```python
if opt_search_overwrite == 'off':
    videoPathList = [path for path in videoPathList if not checkSubtitlesExists(path)]
```

**Comment by emericg** [comment]
Thanks man, it works great and it's also cleaner than before.
We hacked so many features into this script that it's hard to test them all...

Next time send a pull request directly ;)
