### ISSUE TITLE
Specifying download location

### ISSUE THREAD

**Issue by cjaustin1792** [emericg/OpenSubtitlesDownload#37]
Is it possible to specify where the output files go. I want too download subtitles for all my films but they are mounted through a read only drive so I cant write too there separate folders.

**Comment by emericg** [comment]
Hi, this is a weird case.

I definitly won't code this into the script but you can just add this code: 
```
# Custom path
outputdir = "/home/whatever/dir/"
subPath = outputdir + subPath.rsplit('/', 1)[1]
```
in the script, right before "# Download and unzip the selected subtitles".
You can add a custom "-o" option to the argument parsing to customize the output dir pretty easily. Hope that fit your needs.

**Comment by cjaustin1792** [comment]
Thank you very much for this.

**Comment by emericg** [comment]
Allright due to popular demand I actually coded this into the script ^^
You can now use -o with the CLI!
