### ISSUE TITLE
link mdi-maximize-focused hasn't been detected!

### ISSUE THREAD

**Issue by Dxhs** [emericg/OpenSubtitlesDownload#39]
Why am I getting these messages? The program worked a couple weeks ago.
I've updated to the latest version. Same.

Some system info if that helps:
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2 Kernel: 4.15.0-43-generic

`./OpenSubtitlesDownload.py ../Galapagos.With.David.Attenborough.2013.1080p.BluRay.x264/*`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`Unknown option 'text'.`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`Unknown option 'text'.`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`qt.svg: link mdi-maximize-focused hasn't been detected!`
`qt.svg: link mdi-minimize-focused hasn't been detected!`
`Unknown option 'text'.`

**Comment by emericg** [comment]
Closing this issue for now. Feel free to reopen if you have new informations!

**Comment by emericg** [comment]
> Unknown option 'text'

By the way, this was a sign of broken KDE support.
This is now fixed. However if has been broken for years so something else had to change on your own machine to broke the script.
