### ISSUE TITLE
suggsetion: Add the search_overwite option to the ArgumentParser

### ISSUE THREAD

**Issue by YuvalDahn** [emericg/OpenSubtitlesDownload#41]

**Comment by YuvalDahn** [comment]
I want to add the option to add an argument to set opt_search_overwrite to off using an argument in the argument parser.

if you'd like I can make a pull request to add this simple change

**Comment by emericg** [comment]
Yes you can go forward with this. How would you name the option?
I was going to do it tomorrow anyway following discussion on https://github.com/emericg/OpenSubtitlesDownload/pull/40

**Comment by emericg** [comment]
Allright I commited this and named the option -i or --skip. Let me know if that's allright for you.

**Comment by YuvalDahn** [comment]
That's great, Thanks, sorry I didn't got up to writing it myself.
Just a question, what does the -i stands for?

**Comment by emericg** [comment]
It's for 'ignore' ^^ The '-s' is already squatted by '--search'.
I had a hard time finding something that made sense for that option...
In the code, the corresponding setting is named overwrite and is 'on' by default. But using CLI with '--overwrite off' would have been an unnecessary hassle, and '-o' wouldn't have made much more sense anyway. I liked '--once' but it isn't self-explanatory either...
