### ISSUE TITLE
Polish signs

### ISSUE THREAD

**Issue by Frytka** [emericg/OpenSubtitlesDownload#45]
script downloads subtitles without polish signs for example:

> 15
00:01:04,898 --> 00:01:09,278
<i>To ja prowadzi³em nasz¹ organizacjê</i>
<i>przez 20 lat i troszczy³em siê o was.</i>

**Comment by emericg** [comment]
Hi,
Character encoding is a very complicated problem but I can reproduce the issue. Are you experiencing problems on every file or just some of them?
Also, what OS are you using, with the CLI or the GUI?

Fortunately I *think* I have a pretty neat solution that *should* benefit every languages! Can you give the last commit a try and let me know if that solves your problem?
