### ISSUE TITLE
Is there a way to recurse into subdirectories (CLI)?

### ISSUE THREAD

**Issue by mrbig033** [emericg/OpenSubtitlesDownload#48]
I use this program in the command line. My movies are each in a subfolder. Could `OpenSubtitlesDownload` download subtitles for all of them with a single command?

**Comment by mrbig033** [comment]
Yes there is and it's super simple:

`OpenSubtitlesDownload.py /path/*"`

**Comment by emericg** [comment]
There is a pull request still open on this particular issue : https://github.com/emericg/OpenSubtitlesDownload/pull/46
I think I'll allow it on CLI mode. Feel free to weigh in on the PR!

**Comment by mrbig033** [comment]
I'm not sure what you mean by "CLI mode", since I issued the command from the command line. This seems solved to me. Am I mistaken?

**Comment by emericg** [comment]
yes CLI mean commande line.
A patch has been merged, it should recurse when using the CLI now!

**Comment by mrbig033** [comment]
Awesome, thanks!
