### ISSUE TITLE
Add others providers 

### ISSUE THREAD

**Issue by AndersonGI** [emericg/OpenSubtitlesDownload#50]
Sometimes open subtitle cannot provide a subtitle or provides a bad one or the server recuses to connect. So it would be interesting to add others providers like legendastv, podnapsi, tvsubtitles, addic7ed e go on. Subliminal has alredy some code on this https://github.com/Diaoul/subliminal/tree/master/subliminal/providers but it is unmaintained...

**Comment by emericg** [comment]
Yes it certainly possible and it would be pretty cool, but it's also a lot of work, and indeed maintenance.
Also, I always use opensubtitles, I don't really know how good are the others.

**Comment by AndersonGI** [comment]
Yes, I imagine, but at least one more would be cool since just in case.

**Comment by emericg** [comment]
Ok I think I can safely say that this won't happen :/ Sorry!
