### ISSUE TITLE
-i, --skip never work

### ISSUE THREAD

**Issue by ialqwaiz** [emericg/OpenSubtitlesDownload#53]
Hi
Since the opt_language_suffix variable is set to auto, the skip option never works because the downloaded subtitle file name does not match the media file name since it has the language code appended to its name.

I changes the opt_language_suffix variable to off and the skip command works fine.

Thanks

**Comment by emericg** [comment]
Yes actually the function searching for existing file was using the language code provided in opt_languages, so if it was a 3 letter code, it usually wouldn't work with subtitles file with a 2 letter code suffix.
I've improved it to search for every languages (it was only searching for the first one) and with both 3 and 2 letter codes, let me know it works for you now.
