### ISSUE TITLE
missing options

### ISSUE THREAD

**Issue by ialqwaiz** [emericg/OpenSubtitlesDownload#54]
https://github.com/emericg/OpenSubtitlesDownload/blob/5c4ff626e56474c05b2c27f9a1ccdac82cb8b609/OpenSubtitlesDownload.py#L611

The option --skip or -i is not passed to the command in this section.
Suggestion:
`
if not opt_search_overwrite:
        command.append("--skip")
`

**Comment by emericg** [comment]
Yes indeed that was missing and should now be fixed, thanks!
