### ISSUE TITLE
missing options for login

### ISSUE THREAD

**Issue by ialqwaiz** [emericg/OpenSubtitlesDownload#55]
these is no option for changing the username and password to login to the website.

here is my simple fix if you found it useful

after line 504:
`
parser.add_argument('-u', '--username', help="Set opensubtitles.org username")
parser.add_argument('-p', '--password', help="Set opensubtitles.org password")
`

after line 535:
`
if result.username:
      if result.password:
            osd_username = result.username
            osd_password = result.password
`

**Comment by emericg** [comment]
Yes it was on purpose that not every option be mapped to the CLI, but as more and more people seems to be using it, why not.
