### ISSUE TITLE
Unable to change encoding from CP1250 to UTF-8

### ISSUE THREAD

**Issue by kodkuce** [emericg/OpenSubtitlesDownload#58]
Unknown GUI, falling back to an automatic CLI mode
>> Downloading 'Serbian' subtitles for '"His Dark Materials" Armour'
>> OpenSubtitlesDownload encountered an unknown error, sorry about that...
Error: [class 'urllib.error.HTTPError']
Line: 831
Just to be safe, please check....

i wraped it with try except 
and it gived mi then  Error: [class 'NameError'] ...

so i printed subURL
https://dl.opensubtitles.org/en/download/subencoding-utf8/src-api/vrf-19e20c60/sid-rFCWEiFomr8tErX25XQnxKuH8B0/filead/1956564919.gz
in browser it shows [CRITICAL ERROR] Unable to change encoding from CP1250 to UTF-8 ! 
hmm so fast fix i just changed  subencoding-utf8 to subencoding-utf and it now works kinda but ye you need to 
wrap this up i guess :)

**Comment by emericg** [comment]
Hi,
Thank you for investigating this issue!
Unfortunately this is an opensubtitles.org bug. Does it happen often?
And with the way OpenSubtitlesDownload is downloading the subtitles in GUI mode, we can't detect that error. I could work on this for CLI though...

You can disable the utf8 conversion by setting this setting to false:

```
# Force downloading and storing UTF-8 encoded subtitles files.
opt_force_utf8 = False
```

I suspect by setting an invalid encoding ("utf") you achieved the same thing.

**Comment by emericg** [comment]
New versions won't force UTF-8 by default.
