### ISSUE TITLE
false positives... 

### ISSUE THREAD

**Issue by NH-Networks** [emericg/OpenSubtitlesDownload#59]
I've encountered some false positives lately... 

for example 

./OpenSubtitlesDownload.py "The Pale Door 2020 WEBDL-1080p.mkv"
>> Downloading 'Dutch' subtitles for '"Vikings" Death and the Serpent'

./OpenSubtitlesDownload.py "Last Shot 2020 WEBDL-1080p.mkv"
>> Downloading 'Dutch' subtitles for '"The Resident" Last Shot'

opt_search_mode = 'hash_then_filename'

opt_selection_mode = 'auto'

**Comment by emericg** [comment]
Are these results found using the filename search? Do you still have them if you set _opt_search_mode = 'hash'_

Regarding false positive using hashes, it's always been a problem. The hash method itself is not very strong and collisions with other files are very much possible. But the main problem I guess is just subtitles beeing uploaded for the wrong files...
In both cases there is not much to be done unfortunately.

**Comment by emericg** [comment]
Feel free to reopen if you have more insights on this.
