### ISSUE TITLE
Cloudflare DDos protection breaks application?

### ISSUE THREAD

**Issue by henrikmaurin** [emericg/OpenSubtitlesDownload#60]
It seems I can no longer download subtitles. And I think it is because
OpenSubtitles has added Cloudflare DDos protection

This makes OpenSubtitlesDownload respond with
>> Unable to reach opensubtitles.org servers!

**Comment by emericg** [comment]
Isn't that just a temporary server issue? I think cloudfare is used since the begining of this year at least.
However since today (worked yesterday), I had to use my osd account, because of "401 unauthorized" error...

**Comment by henrikmaurin** [comment]
It might me temporary. I might have come to the wrong conclusions.
I have entered my credentials, but still get errors. 

Lets hope it corrects itself.

**Comment by emericg** [comment]
Well you don't have a 401 error so it's not the same thing, but the timing is uncanny.
I've just read that they can ban unauthorized users for 24h, so let me know if it does solves itself or if we need to have another look at it.

**Comment by henrikmaurin** [comment]
Ok. Will test tomorrow and report back

**Comment by henrikmaurin** [comment]
I ran the script through a VPN. Got results. So I guess my IP is quarantined.
I believe we can close this issue. Thanks for your time!
