### ISSUE TITLE
In order to continue OpenSubtitles.org subtitles service you need to Log In

### ISSUE THREAD

**Issue by Gahamelas** [emericg/OpenSubtitlesDownload#62]
I managed to make it work :) 
However, my subtitles files look all like this:
1
```
00:00:00,001 --> 04:00:00,000
In order to continue OpenSubtitles.org
subtitles service you need to Log In
```

I am logged in my browser in my OpenSubtitles account but it won't work.
Thanks!

**Comment by emericg** [comment]
Hi, did you set your credentials inside the script too? Like described here: https://github.com/emericg/OpenSubtitlesDownload/wiki/Adjust-settings#log-in-with-a-registered-user

You can also use the --username and --password CLI option, if you are on the version 4.2

**Comment by Gahamelas** [comment]
Thanks, you're a genius. It works!
