### ISSUE TITLE
Desktop files not working

### ISSUE THREAD

**Issue by ignapk** [emericg/OpenSubtitlesDownload#66]
When launching OpenSubtitlesDownload by right clicking on the video file in nautilus and selecting Open with other application->OpenSubtitlesDownload, it fails due to quotation marks in the OpenSubtitlesDownload-gnome.desktop exec line, removing them solves the issue.

**Comment by emericg** [comment]
Yes these desktop files are old...
I've updated them and even did the wiki page for [linux installation](https://github.com/emericg/OpenSubtitlesDownload/wiki/Installation-on-linux) (after procrastinating on this for 10 years)

Thanks!
