### ISSUE TITLE
Unexpected error (line 768): <class 'AttributeError'>

### ISSUE THREAD

**Issue by hboetes** [emericg/OpenSubtitlesDownload#69]
Since the latest git version I run into this error:

```
% subtitledownload Some.Movie.20xx.ip.XviD.AC3-EVO.avi
Unknown GUI, falling back to an automatic CLI mode
Unexpected error (line 768): <class 'AttributeError'>
```

**Comment by hboetes** [comment]
I just checked out d07bc9488592b1b4872437b00371aef291058863 and that works fine.

**Comment by hboetes** [comment]
```
% python --version
Python 3.9.1
```

**Comment by ema07cqc** [comment]
> Since the latest git version I run into this error:
> 
> ```
> % subtitledownload Some.Movie.20xx.ip.XviD.AC3-EVO.avi
> Unknown GUI, falling back to an automatic CLI mode
> Unexpected error (line 768): <class 'AttributeError'>
> ```

I have the same error. already know how to fix it? thanks.

**Comment by ema07cqc** [comment]
> > Since the latest git version I run into this error:
> > ```
> > % subtitledownload Some.Movie.20xx.ip.XviD.AC3-EVO.avi
> > Unknown GUI, falling back to an automatic CLI mode
> > Unexpected error (line 768): <class 'AttributeError'>
> > ```
> 
> I have the same error. already know how to fix it? thanks.

Fixed using this version 
https://github.com/emericg/OpenSubtitlesDownload/raw/18d17897187321895c0b61f72ff3431a275e55a8/OpenSubtitlesDownload.py

**Comment by kryzar** [comment]
Hi,

I am having the same issue:

```
Unexpected error (line 768): <class 'AttributeError'>
```

It occurs when the variable `opt_selection_mode` is set to `'auto'` in the file `OpenSubtitlesDownload.py`. If I set the variable to `'default'`, then there is no problem. I am running version **6f18f4434f1a5ecc031213c6b95100bde3f94a4e**.

**Comment by emericg** [comment]
Sorry guys I wasn't home this week. This should be fixed now!

**Comment by hboetes** [comment]
Yes, the problem has been solved. Thanks.

**Comment by emericg** [comment]
Thanks for testing guys!

**Comment by kryzar** [comment]
Hey no problem! Your project is very useful.
