### ISSUE TITLE
How do you install this on KDE?

### ISSUE THREAD

**Issue by Sojiro84** [emericg/OpenSubtitlesDownload#77]
There is a explanation for Gnome, but I can't find info on how to install this on KDE so I can use it on the right-click menu on video files.

Thanks in advance.

**Comment by Sojiro84** [comment]
Ahh, guide was on the wiki and not the frontpage of the repo: https://github.com/emericg/OpenSubtitlesDownload/wiki/Installation-on-linux

Did the local install but getting the error it can't find the *.py.

Hmm.

**Comment by emericg** [comment]
Hi.
Did you edit the desktop file, to set the full path to the python script?

```
edit the exec= line from the desktop file, and customize it like if you were using the CLI (see that wiki page)
```
