### ISSUE TITLE
Language suffix options are ignored

### ISSUE THREAD

**Issue by Stooovie** [emericg/OpenSubtitlesDownload#83]
OpenSubtitlesDownload 5.0 on Mac Big Sur 11.6. 

I have these options:
```
opt_languages = ['eng','cze']
opt_language_suffix = 'on'
opt_language_suffix_size = '2'
opt_language_suffix_separator = '.'
```
Script outputs `Free Guy (2021)_eng.srt` anyway. Please help.

**Comment by emericg** [comment]
I don't know, I've tried the same options and its working fine.
Can you make sure these options are saved in the right file and try again on a couple of media?

**Comment by Stooovie** [comment]
hi, it seems to work fine now. I don't know what was the culprit. Case closed, thank you.

**Comment by emericg** [comment]
Alright good to know :)
