### ISSUE TITLE
Unexpected error (line 774): <class 'ValueError'>

### ISSUE THREAD

**Issue by Roshri** [emericg/OpenSubtitlesDownload#86]
Hi! Thanks for this great tool, I just discovered it today and I'm trying it out, but when I try to use it I get this error `Unexpected error (line 774): <class 'ValueError'>`

line 774 is this one ` (subName, subIndex) = selectionAuto(subtitlesResultList)`

So this only happens when leaving it to auto, if I manually select which sub to download it works !
I'm using it on Windows

**Comment by emericg** [comment]
Please reopen this issue if the latest version still run into this error.
