### ISSUE TITLE
(opt_language_suffix_separator) not working file_en.srt

### ISSUE THREAD

**Issue by naifmalharthi** [emericg/OpenSubtitlesDownload#87]
# Character used to separate file path from the language code (ex: file_en.srt).
opt_language_suffix_separator = 'file_en.srt'

When I change to a title, for example, English or French, it does not put the symbol in the translation, for example:
movie.fr.srt

Tried binary and triple encoding. like : en or eng
movie.mkv
movie.srt

I want to be like :
movie.mkv
movie.en.srt OR movie.eng.srt

* Sorry for my bad language.

**Comment by emericg** [comment]
I'm sorry I don't really understand your issue.

opt_language_suffix_separator is a single character. Simply use '.' or '_'.

If you want to change the language code size, change opt_language_suffix_size to '2' or '3'.

If you want to force the use of a language code set opt_language_suffix to 'on'
