### ISSUE TITLE
Opensubtitles cli given 401 unauthorized error 

### ISSUE THREAD

**Issue by giridhar7889** [emericg/OpenSubtitlesDownload#89]
I have created an account on opensubtitles.org and I'm not sure how to use my registered username and password with the opensubtitiles cli on windows.Can someone help me with this .
Thank you.
![image](https://user-images.githubusercontent.com/62104626/163942682-46281d23-0868-4562-a7a4-0dfa19f2e6bd.png)

**Comment by giridhar7889** [comment]
And after using --username and --password arguments on cli . I'm getting unrecognized argument error.
![image](https://user-images.githubusercontent.com/62104626/163944131-69f4641b-9a35-4f4b-b3a7-e33e34f84677.png)

**Comment by giridhar7889** [comment]
OHH SHOOT !!.
I forgot to modify my username and password in OpenSubtitleDownload.py file .Btw please update the argument list in the next version to include username and password through CLI .

**Comment by emericg** [comment]
I don't think you are using the latest version (5.0), it should fix your issue.
