### ISSUE TITLE
finding and downloading subtitles takes a lot of time.

### ISSUE THREAD

**Issue by pashosh** [emericg/OpenSubtitlesDownload#91]
i'm on archlinux + gnome.
from yesterday when i try to search for subtitles (using right click on files, in nautilus), it takes couple of *minutes* (4 minutes in the last time i checked) till it "finds" them.
then, when i download the subtitles, it also takes couple of minutes to download it.
it is happening with every video file i'm trying to download subtitles for.
in the config file, i set my username and password for opensubtitles.
everything is set as it should be, but suddenly this happened...

**Comment by emericg** [comment]
Yes I can confirm that, but I'm at a loss to understand what's happening.
I can see that what takes minutes is the very first call to connect to the opensubtitles API, yet the login call says it took 0.25s

**Comment by emericg** [comment]
Ok it seems that the problem fixed itself.
Something probably required maintenance on the opensubtitles servers...

**Comment by pashosh** [comment]
thanks :-)
