### ISSUE TITLE
Opensubtitles login not working in CLI

### ISSUE THREAD

**Issue by bjuncek** [emericg/OpenSubtitlesDownload#93]
I have a headless nas where I want to download the subtitles for videos I have on there.
Running the script with edited username/pass and/or `--username` and `--password` arguments still produces the 401 error.

**Comment by JayKuswahey** [comment]
@bjuncek can you make absolutely sure there's no "weird" characters (things  like `'` or `~` or backticks) in the username or password that can brick the quotation of the script/command? 

Do you keep them quoted when you put them in the script?

Can you change your password on opensubtitles website to something with only lowercase letters and test that? 

I can't add anything beyond "it works" on my machine, lowercase letter, uppercase letters, digits, `-` and `@` in it.

**Comment by emericg** [comment]
This issue needs to be run again with the very latest version of this script, that's running with a new provider (opensubtitles.COM) and new accounts.
If you still have troubles logging in, feel free to reopen this issue.
