### ISSUE TITLE
OpenSubtitlesDownload not working for some subtitles, even though they exists.

### ISSUE THREAD

**Issue by wantedda443** [emericg/OpenSubtitlesDownload#94]
Hi emericg

Thank you for a wonderful tool.

I have one problem, OpenSubtitlesDownload can't find subtitles for some movies, even though a search on Opensubtitles.org easily finds them. One example: The.Outfit.2022.1080p.AMZN.WEB-DL.DDP5.1.H.264-EVO.mkv

I've tried with hash search, filename search and both (then & and) but I get this output: >> No subtitles found for this video

Most subtitles the tools finds no problem.

I'm running on Ubuntu 20.04 and the command I use is: OpenSubtitles.py --cli --auto `filename`

**Comment by emericg** [comment]
The new API is now implemented in the script, so I'll close this issue.
Please reopen the issue if you have troubles with the new version as well.

**Comment by emericg** [comment]
And by the way, I can confirm that the "search by filename" does find more results now.
Not sure that it's the case with the "search by hash" but as @lwouis mentioned, it's possible.
