### ISSUE TITLE
Unexpected error (line 862): <class 'UnicodeEncodeError'>

### ISSUE THREAD

**Issue by danzig666** [emericg/OpenSubtitlesDownload#96]
UnicodeEncodeError, command line was:
`python OpenSubtitlesDownload.py -u user -p pass --cli -l hun -8 c:\path\ -a -i -x`

Quick fix:
`byteswritten = open(subPath, 'w', encoding='utf-8').write(decodedStr)`

**Comment by emericg** [comment]
The v6 version with the new opensubtitles.com always download subtitles in UTF8 encoded format, and the code you mention is not in the script anymore.

Feel free to reopen an issue if similar problems (related to subtitles encoding) are found with the new provider.
