### ISSUE TITLE
It would be nice to have a cli option to show/hide "hearing impaired (HI)" results for English subtitles

### ISSUE THREAD

**Issue by rasitayaz** [emericg/OpenSubtitlesDownload#98]
Thanks for this useful script. When displaying English subtitles using cli, HI results are showing `> "HI"` after the title, which is a great idea and helpful for distinguishing them. And I'm assuming the same information can be used with a cli option to filter out them.

**Comment by emericg** [comment]
Alright, version 6.1 adds a way to do that, either set `opt_ignore_hi = True` or use **--nohi** with the CLI. Thanks for the suggestion.
